# Generated by Django 3.2.6 on 2021-08-14 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('initial_frequency', models.FloatField(blank=True, null=True)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('target_frequency', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cause',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CauseBarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('pfd', models.FloatField(blank=True, null=True)),
                ('cause_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cause_barrier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Consequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('initial_frequency', models.FloatField(blank=True, null=True)),
                ('target_frequency', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consequence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsequenceBarrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('pfd', models.FloatField(blank=True, null=True)),
                ('consequence_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'consequence_barrier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('cause_id', models.IntegerField(blank=True, null=True)),
                ('consequence_id', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'event',
                'managed': False,
            },
        ),
    ]
